flags = {
    "🇦🇫": ["Kabul", "kabul", "Кабул", "кабул"],
    "🇦🇱": ["Tirana", "tirana", "Тирана", "тирана"],
    "🇩🇿": ["Algiers", "algiers", "Алжир", "алжир"],
    "🇦🇸": ["Pago Pago", "pago pago", "Паго‑Паго", "паго‑паго"],
    "🇦🇩": ["Andorra la Vella", "andorra la vella", "Андорра‑ла‑Велья", "андорра‑ла‑велья"],
    "🇦🇴": ["Luanda", "luanda", "Луанда", "луанда"],
    "🇦🇮": ["The Valley", "the valley", "Валли", "валли"],
    "🇦🇶": ["–", "–", "–", "–"],
    "🇦🇬": ["St. John's", "st. john's", "Сент‑Джонс", "сент‑джонс"],
    "🇦🇷": ["Buenos Aires", "buenos aires", "Буэнос‑Айрес", "буэнос‑айрес"],
    "🇦🇲": ["Yerevan", "yerevan", "Ереван", "ереван"],
    "🇦🇼": ["Oranjestad", "oranjestad", "Ораньестад", "ораньестад"],
    "🇦🇺": ["Canberra", "canberra", "Канберра", "канберра"],
    "🇦🇹": ["Vienna", "vienna", "Вена", "вена"],
    "🇦🇿": ["Baku", "baku", "Баку", "баку"],
    "🇧🇸": ["Nassau", "nassau", "Нассау", "нассау"],
    "🇧🇭": ["Manama", "manama", "Манама", "манама"],
    "🇧🇩": ["Dhaka", "dhaka", "Дакка", "дакка"],
    "🇧🇧": ["Bridgetown", "bridgetown", "Бриджтаун", "бриджтаун"],
    "🇧🇾": ["Minsk", "minsk", "Минск", "минск"],
    "🇧🇪": ["Brussels", "brussels", "Брюссель", "брюссель"],
    "🇧🇿": ["Belmopan", "belmopan", "Бельмопан", "бельмопан"],
    "🇧🇯": ["Porto‑Novo", "porto‑novo", "Порту‑Ново", "порту‑ново"],
    "🇧🇹": ["Thimphu", "thimphu", "Тхимпху", "тхимпху"],
    "🇧🇴": ["Sucre", "sucre", "Сукре", "сукре"],
    "🇧🇦": ["Sarajevo", "sarajevo", "Сараево", "сараево"],
    "🇧🇼": ["Gaborone", "gaborone", "Габороне", "габороне"],
    "🇧🇷": ["Brasília", "brasília", "Бразилиа", "бразилия"],
    "🇧🇳": ["Bandar Seri Begawan", "bandar seri begawan", "Бандар‑Сери‑Бегаван", "бандар‑сери‑бегаван"],
    "🇧🇬": ["Sofia", "sofia", "София", "софия"],
    "🇧🇫": ["Ouagadougou", "ouagadougou", "Уа‑гаду‑гу", "уа‑гаду‑гу"],
    "🇧🇮": ["Gitega", "gitega", "Гитега", "гитега"],
    "🇨🇻": ["Praia", "praia", "Прая", "прая"],
    "🇰🇭": ["Phnom Penh", "phnom penh", "Пномпень", "пномпень"],
    "🇨🇲": ["Yaoundé", "yaoundé", "Яунде", "яунде"],
    "🇨🇦": ["Ottawa", "ottawa", "Оттава", "оттава"],
    "🇰🇾": ["George Town", "george town", "Джордж‑таун", "джордж‑таун"],
    "🇨🇫": ["Bangui", "bangui", "Банги", "банги"],
    "🇹🇩": ["N'Djamena", "n'djamena", "Нджамена", "нджамена"],
    "🇨🇱": ["Santiago", "santiago", "Сантьяго", "сантьяго"],
    "🇨🇳": ["Beijing", "beijing", "Пекин", "пекин"],
    "🇨🇴": ["Bogotá", "bogotá", "Богота", "богота"],
    "🇰🇲": ["Moroni", "moroni", "Морони", "морони"],
    "🇨🇬": ["Brazzaville", "brazzaville", "Браззавиль", "браззавиль"],
    "🇨🇩": ["Kinshasa", "kinshasa", "Киншаса", "киншаса"],
    "🇨🇷": ["San José", "san josé", "Сан‑Хосе", "сан‑хосе"],
    "🇭🇷": ["Zagreb", "zagreb", "Загреб", "загреб"],
    "🇨🇺": ["Havana", "havana", "Гавана", "гавана"],
    "🇨🇾": ["Nicosia", "nicosia", "Никосия", "никосия"],
    "🇨🇿": ["Prague", "prague", "Прага", "прага"],
    "🇩🇰": ["Copenhagen", "copenhagen", "Копенгаген", "копенгаген"],
    "🇩🇯": ["Djibouti", "djibouti", "Джибути", "джибути"],
    "🇩🇲": ["Roseau", "roseau", "Розо", "розо"],
    "🇩🇴": ["Santo Domingo", "santo domingo", "Санто‑Доминго", "санто‑доминико"],
    "🇪🇨": ["Quito", "quito", "Кито", "кито"],
    "🇪🇬": ["Cairo", "cairo", "Каир", "каир"],
    "🇸🇻": ["San Salvador", "san salvador", "Сан‑Сальвадор", "сан‑сальвадор"],
    "🇬🇶": ["Malabo", "malabo", "Малабо", "малабо"],
    "🇪🇷": ["Asmara", "asmara", "Асмэра", "асмэра"],
    "🇪🇪": ["Tallinn", "tallinn", "Таллин", "таллин"],
    "🇸🇿": ["Mbabane", "mbabane", "Мбабане", "мбабане"],
    "🇪🇹": ["Addis Ababa", "addis ababa", "Аддис‑Абеба", "аддис‑абеба"],
    "🇫🇯": ["Suva", "suva", "Сува", "сува"],
    "🇫🇮": ["Helsinki", "helsinki", "Хельсинки", "хельсинки"],
    "🇫🇷": ["Paris", "paris", "Париж", "париж"],
    "🇬🇦": ["Libreville", "libreville", "Либревиль", "либревиль"],
    "🇬🇲": ["Banjul", "banjul", "Банджул", "банджул"],
    "🇩🇪": ["Berlin", "berlin", "Берлин", "берлин"],
    "🇬🇭": ["Accra", "accra", "Аккра", "аккра"],
    "🇬🇷": ["Athens", "athens", "Афины", "афины"],
    "🇬🇩": ["St. George's", "st. george's", "Сент‑Джорджес", "сент‑джорджес"],
    "🇬🇺": ["Hagåtña", "hagåtña", "Агатона", "агатона"],
    "🇬🇹": ["Guatemala City", "guatemala city", "Гватемала", "гватемала"],
    "🇬🇳": ["Conakry", "conakry", "Конакри", "конакри"],
    "🇬🇫": ["Cayenne", "cayenne", "Кайенна", "кайенна"],
    "🇬🇪": ["Tbilisi", "tbilisi", "Тбилиси", "тбилиси"],
    "🇬🇮": ["Gibraltar", "gibraltar", "Гибралтар", "гибралтар"],
    "🇬🇼": ["Bissau", "bissau", "Бисау", "бисау"],
    "🇬🇾": ["Georgetown", "georgetown", "Джорджтаун", "джорджтаун"],
    "🇭🇹": ["Port‑au‑Prince", "port‑au‑prince", "Порт‑о‑Пренс", "порт‑о‑пренс"],
    "🇭🇳": ["Tegucigalpa", "tegucigalpa", "Тегусигальпа", "тегусигальпа"],
    "🇭🇰": ["Hong Kong", "hong kong", "Гонконг", "гонконг"],
    "🇭🇺": ["Budapest", "budapest", "Будапешт", "будапешт"],
    "🇮🇳": ["New Delhi", "new delhi", "Нью‑Дели", "нью‑дели"],
    "🇮🇩": ["Jakarta", "jakarta", "Джакарта", "джакарта"],
    "🇮🇷": ["Tehran", "tehran", "Тегеран", "тегеран"],
    "🇮🇶": ["Baghdad", "baghdad", "Багдад", "багдад"],
    "🇮🇪": ["Dublin", "dublin", "Дублин", "дублин"],
    "🇮🇱": ["Jerusalem", "jerusalem", "Иерусалим", "иерусалим"],
    "🇮🇹": ["Rome", "rome", "Рим", "рим"],
    "🇯🇵": ["Tokyo", "tokyo", "Токио", "токио"],
    "🇯🇴": ["Amman", "amman", "Амман", "амман"],
    "🇰🇿": ["Astana", "astana", "Астана", "астана"],
    "🇰🇪": ["Nairobi", "nairobi", "Найроби", "найроби"],
    "🇰🇮": ["Tarawa", "tarawa", "Тарава", "тарава"],
    "🇰🇼": ["Kuwait City", "kuwait city", "Кувейт‑Сити", "кувейт‑сити"],
    "🇰🇬": ["Bishkek", "bishkek", "Бишкек", "бишкек"],
    "🇱🇦": ["Vientiane", "vientiane", "Вьентьян", "вьентьян"],
    "🇱🇻": ["Riga", "riga", "Рига", "рига"],
    "🇱🇧": ["Beirut", "beirut", "Бейрут", "бейрут"],
    "🇱🇸": ["Maseru", "maseru", "Масеру", "масеру"],
    "🇱🇷": ["Monrovia", "monrovia", "Монровия", "монровия"],
    "🇱🇾": ["Tripoli", "tripoli", "Триполи", "триполи"],
    "🇱🇹": ["Vilnius", "vilnius", "Вильнюс", "вильнюс"],
    "🇱🇺": ["Luxembourg", "luxembourg", "Люксембург", "люксембург"],
    "🇲🇰": ["Skopje", "skopje", "Скопье", "скопье"],
    "🇲🇬": ["Antananarivo", "antananarivo", "Антананариву", "антананариву"],
    "🇲🇼": ["Lilongwe", "lilongwe", "Лилонгве", "лилонгве"],
    "🇲🇻": ["Malé", "malé", "Мале", "мале"],
    "🇲🇱": ["Bamako", "bamako", "Бамако", "бамако"],
    "🇲🇹": ["Valletta", "valletta", "Валлетта", "валлетта"],
    "🇲🇷": ["Nouakchott", "nouakchott", "Нуакшот", "нуакшот"],
    "🇲🇺": ["Port Louis", "port louis", "Порт‑Луи", "порт‑луи"],
    "🇲🇽": ["Mexico City", "mexico city", "Мехико", "мехико"],
    "🇲🇩": ["Chisinau", "chisinau", "Кишинёв", "кишинёв"],
    "🇲🇨": ["Monaco", "monaco", "Монако", "монако"],
    "🇲🇳": ["Ulaanbaatar", "ulaanbaatar", "Улан‑Батор", "улан‑батор"],
    "🇲🇪": ["Podgorica", "podgorica", "Подгорица", "подгорица"],
    "🇲🇦": ["Rabat", "rabat", "Рабат", "рабат"],
    "🇲🇿": ["Maputo", "maputo", "Мапуту", "мапуту"],
    "🇳🇦": ["Windhoek", "windhoek", "Виндхук", "виндхук"],
    "🇳🇵": ["Kathmandu", "kathmandu", "Катманду", "катманду"],
    "🇳🇱": ["Amsterdam", "amsterdam", "Амстердам", "амстердам"],
    "🇳🇿": ["Wellington", "wellington", "Веллингтон", "веллингтон"],
    "🇳🇮": ["Managua", "managua", "Манагуа", "манагуа"],
    "🇳🇬": ["Abuja", "abuja", "Абуджа", "абуджа"],
    "🇳🇴": ["Oslo", "oslo", "Осло", "осло"],
    "🇴🇲": ["Muscat", "muscat", "Мускат", "мускат"],
    "🇵🇰": ["Islamabad", "islamabad", "Исламабад", "исламабад"],
    "🇵🇦": ["Panama City", "panama city", "Панама‑Сити", "панама‑сити"],
    "🇵🇬": ["Port Moresby", "port moresby", "Порт‑Морсби", "порт‑морсби"],
    "🇵🇾": ["Asunción", "asunción", "Асунсьон", "асунсьон"],
    "🇵🇪": ["Lima", "lima", "Лима", "лима"],
    "🇵🇭": ["Manila", "manila", "Манила", "манила"],
    "🇵🇱": ["Warsaw", "warsaw", "Варшава", "варшава"],
    "🇵🇹": ["Lisbon", "lisbon", "Лиссабон", "лиссабон"],
    "🇶🇦": ["Doha", "doha", "Доха", "доха"],
    "🇷🇴": ["Bucharest", "bucharest", "Бухарест", "бухарест"],
    "🇷🇺": ["Moscow", "moscow", "Москва", "москва"],
    "🇷🇼": ["Kigali", "kigali", "Кигали", "кигали"],
    "🇸🇹": ["São Tomé", "são tomé", "Сан‑Томе", "сан‑томе"],
    "🇸🇦": ["Riyadh", "riyadh", "Эр‑Рияд", "эр‑рияд"],
    "🇸🇳": ["Dakar", "dakar", "Дакар", "дакaр"],
    "🇷🇸": ["Belgrade", "belgrade", "Белград", "белград"],
    "🇸🇨": ["Victoria", "victoria", "Виктория", "виктория"],
    "🇸🇱": ["Freetown", "freetown", "Фритаун", "фритаун"],
    "🇸🇬": ["Singapore", "singapore", "Сингапур", "сингапур"],
    "🇸🇰": ["Bratislava", "bratislava", "Братислава", "братислава"],
    "🇸🇮": ["Ljubljana", "ljubljana", "Любляна", "любляна"],
    "🇸🇧": ["Honiara", "honiara", "Хониара", "хониара"],
    "🇸🇴": ["Mogadishu", "mogadishu", "Могадишо", "могадишо"],
    "🇿🇦": ["Pretoria", "pretoria", "Претория", "претория"],
    "🇰🇷": ["Seoul", "seoul", "Сеул", "сеул"],
    "🇪🇸": ["Madrid", "madrid", "Мадрид", "мадрид"],
    "🇱🇰": ["Sri Jayawardenepura Kotte", "sri jayawardenepura kotte", "Сри‑Джаяварденепура‑Котте", "сри‑джаяварденепура‑котте"],
    "🇸🇩": ["Khartoum", "khartoum", "Хартум", "хартум"],
    "🇸🇷": ["Paramaribo", "paramaribo", "Парамарибо", "парамарибо"],
    "🇸🇪": ["Stockholm", "stockholm", "Стокгольм", "стокгольм"],
    "🇨🇭": ["Bern", "bern", "Берн", "берн"],
    "🇸🇾": ["Damascus", "damascus", "Дамаск", "дамаск"],
    "🇹🇯": ["Dushanbe", "dushanbe", "Душанбе", "душанбе"],
    "🇹🇿": ["Dodoma", "dodoma", "Додома", "додома"],
    "🇹🇭": ["Bangkok", "bangkok", "Бангкок", "бангкок"],
    "🇹🇬": ["Lomé", "lomé", "Ломе", "ломе"],
    "🇹🇴": ["Nukuʻalofa", "nukuʻalofa", "Нукуалофа", "нукуалофа"],
    "🇹🇹": ["Port of Spain", "port of spain", "Порт‑оф‑Спейн", "порт‑оф‑спейн"],
    "🇹🇳": ["Tunis", "tunis", "Тунис", "тунис"],
    "🇹🇷": ["Ankara", "ankara", "Анкара", "анкара"],
    "🇹🇲": ["Ashgabat", "ashgabat", "Ашхабад", "ашхабад"],
    "🇺🇬": ["Kampala", "kampala", "Кампала", "кампала"],
    "🇺🇦": ["Kyiv", "kyiv", "Киев", "киев"],
    "🇦🇪": ["Abu Dhabi", "abu dhabi", "Абу‑Даби", "абу‑даби"],
    "🇬🇧": ["London", "london", "Лондон", "лондон"],
    "🇺🇸": ["Washington, D.C.", "washington, d.c.", "Вашингтон", "вашингтон"],
    "🇺🇾": ["Montevideo", "montevideo", "Монтевидео", "монтевидео"],
    "🇺🇿": ["Tashkent", "tashkent", "Ташкент", "ташкент"],
    "🇻🇺": ["Port Vila", "port vila", "Порт‑Вила", "порт‑вила"],
    "🇻🇪": ["Caracas", "caracas", "Каракас", "каракс"],
    "🇻🇳": ["Hanoi", "hanoi", "Ханой", "ханой"],
    "🇾🇪": ["Sana'a", "sana'a", "Сана", "сана"],
    "🇿🇲": ["Lusaka", "lusaka", "Лусака", "лусака"],
    "🇿🇼": ["Harare", "harare", "Хараре", "хараре"]
}